Path = "13ff357119be4b689eb7521525d840b1"
OPENAI_API_KEY = "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"
CONNECTION_STRING = "postgresql+psycopg2://xavinine:Onimush484!@xavinine.postgres.database.azure.com:5432/postgres"
COLLECTION_NAME = "honnes"