Path = "13ff357119be4b689eb7521525d840b1"
OPENAI_API_KEY = "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"
CONNECTION_STRING = "postgresql+psycopg2://xavinine:Onimush484!@xavinine.postgres.database.azure.com:5432/postgres"
COLLECTION_NAME = "honnes"