Path = "13ff357119be4b689eb7521525d840b1"
OPENAI_API_KEY = "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"
CONNECTION_STRING = "postgresql+psycopg2://xavinine:Onimush484!@xavinine.postgres.database.azure.com:5432/postgres"
COLLECTION_NAME = "boss"